/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;


//import static bestproject.Login.search3;
import static bestproject.employee.members;
import java.util.*;
import java.awt.Component;
import java.awt.event.ItemEvent;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.Renderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;


/**
 *
 * @author HP
 */
public class diet_rot extends javax.swing.JFrame {
member m = new member ();
Diet_routine d;

    /**
     * Creates new form diet_rot
     */
    public diet_rot() {
        initComponents();
        this.setLocationRelativeTo(null);
   
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(false);} 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        day_combo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        photo7 = new javax.swing.JLabel();
        photo6 = new javax.swing.JLabel();
        photo5 = new javax.swing.JLabel();
        photo4 = new javax.swing.JLabel();
        photo3 = new javax.swing.JLabel();
        photo1 = new javax.swing.JLabel();
        photo2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("7-Day Meal Plan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 494));

        jPanel1.setLayout(null);

        day_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        day_combo.setForeground(new java.awt.Color(0, 102, 51));
        day_combo.setMaximumRowCount(4);
        day_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Day", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thrusday", "Friday" }));
        day_combo.setToolTipText("");
        day_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day_combo.setPreferredSize(new java.awt.Dimension(5, 5));
        day_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                day_comboItemStateChanged(evt);
            }
        });
        day_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_comboActionPerformed(evt);
            }
        });
        jPanel1.add(day_combo);
        day_combo.setBounds(200, 50, 160, 30);

        jTable1.setBackground(new java.awt.Color(0, 102, 51));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Breakfast", "Lunch", "Dinner"
            }
        ));
        jTable1.setRowHeight(300);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Breakfast");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Lunch");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Dinner");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 280, 670, 170);

        photo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet6.jpg"))); // NOI18N
        jPanel1.add(photo7);
        photo7.setBounds(290, 130, 340, 150);

        photo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet5.jpg"))); // NOI18N
        jPanel1.add(photo6);
        photo6.setBounds(290, 130, 340, 150);

        photo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet4.jpg"))); // NOI18N
        jPanel1.add(photo5);
        photo5.setBounds(290, 130, 340, 150);

        photo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet2.jpg"))); // NOI18N
        jPanel1.add(photo4);
        photo4.setBounds(290, 130, 340, 150);

        photo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet1.jpg"))); // NOI18N
        jPanel1.add(photo3);
        photo3.setBounds(290, 130, 340, 150);

        photo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/carb-cycling-slider.jpg"))); // NOI18N
        jPanel1.add(photo1);
        photo1.setBounds(290, 130, 340, 150);

        photo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet.jpg"))); // NOI18N
        jPanel1.add(photo2);
        photo2.setBounds(290, 130, 340, 150);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 440, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/diet_rot.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 900, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void day_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_comboActionPerformed
  
        
  if (day_combo.getSelectedIndex() == 0) {
             JOptionPane.showMessageDialog(null,"can't Select this option ", "ERROR", JOptionPane.ERROR_MESSAGE);
         }
          
  else if(day_combo.getSelectedIndex() >0){
      
      if(day_combo.getSelectedIndex()==1){
   

    photo1.setVisible(true);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(false);}
      if(day_combo.getSelectedIndex()==2){
   

       photo1.setVisible(false);
    photo2.setVisible(true);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(false);}
       if(day_combo.getSelectedIndex()==3){
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(true);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(false);}
       if(day_combo.getSelectedIndex()==4){
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(true);
    photo7.setVisible(false);}
        if(day_combo.getSelectedIndex()==5){
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(true);
    photo6.setVisible(false);
    photo7.setVisible(false);}
         if(day_combo.getSelectedIndex()==6){
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(true);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(false);}
          if(day_combo.getSelectedIndex()==7){
   

       photo1.setVisible(false);
    photo2.setVisible(false);
    photo3.setVisible(false);
    photo4.setVisible(false);
    photo5.setVisible(false);
    photo6.setVisible(false);
    photo7.setVisible(true);}
      
           int i=Login.search3(Login.text_name.getText(), Login.text_Password.getText());
       if(members.get(i).getType().equals("football player"))
       {
       d=m.Diet_Routine(day_combo.getSelectedIndex()-1,"football player");
       }
       else if(members.get(i).getType().equals("swimming player"))
       {
           d=m.Diet_Routine(day_combo.getSelectedIndex()-1,"swimming player");
       }
       else if(members.get(i).getType().equals("diabetes patient"))
       {
         d=m.Diet_Routine(day_combo.getSelectedIndex()-1,"diabetes patient");
       }
       else if(members.get(i).getType().equals("pregnancy"))
       {
           d=m.Diet_Routine(day_combo.getSelectedIndex()-1,"pregnancy");
       }
       

DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
 model.getDataVector().removeAllElements();
       Object rowData[] = new Object[3];
           rowData[0]=  d.breakfast;
           rowData[1]=  d.lunch;
            rowData[2]=  d.dinner;
           model.addRow( rowData);
           day_combo.setSelectedIndex(0);
         }
   jTable1.setDefaultRenderer(Object.class, new multiline());

    }//GEN-LAST:event_day_comboActionPerformed

    private void day_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_day_comboItemStateChanged
       
      
    
        
    }//GEN-LAST:event_day_comboItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

            mem_op uu=new mem_op();
            uu.setVisible(true);
            uu.pack();
            uu.setLocationRelativeTo(null);
            this.dispose();
       
           
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diet_rot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diet_rot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diet_rot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diet_rot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diet_rot().setVisible(true);
            }
        });
    }
public class multiline extends JTextArea implements TableCellRenderer{

    private List<List<Integer>> rowcolHeight = new ArrayList<>();
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText((value==null) ? "" : value.toString());
            setEditable(false);
           
            return this;
        }
} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox day_combo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel photo1;
    private javax.swing.JLabel photo2;
    private javax.swing.JLabel photo3;
    private javax.swing.JLabel photo4;
    private javax.swing.JLabel photo5;
    private javax.swing.JLabel photo6;
    private javax.swing.JLabel photo7;
    // End of variables declaration//GEN-END:variables
}
