/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;
import static bestproject.employee.members;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class edit_memb1ff extends javax.swing.JFrame {
  int id_check;
     employee e = new employee();
   
     
    public edit_memb1ff() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        edit_btn = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        u_name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_Name", "Name", "ID", "Type", "Height", "Weight", "Gender", "Age"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 260, 600, 130);

        edit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(edit_btn);
        edit_btn.setBounds(400, 410, 90, 25);
        jPanel1.add(id);
        id.setBounds(330, 60, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User_Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 120, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Weight");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 150, 49, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Height");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 180, 50, 20);

        n.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n.setText("Name");
        jPanel1.add(n);
        n.setBounds(530, 120, 40, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 150, 50, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 180, 40, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 210, 50, 17);

        search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn);
        search_btn.setBounds(410, 100, 80, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Please Enter Member's ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 20, 234, 22);
        jPanel1.add(gender);
        gender.setBounds(230, 210, 140, 20);
        jPanel1.add(u_name);
        u_name.setBounds(230, 120, 140, 20);
        jPanel1.add(age);
        age.setBounds(600, 180, 130, 20);
        jPanel1.add(height);
        height.setBounds(230, 180, 140, 20);
        jPanel1.add(name);
        name.setBounds(600, 120, 130, 20);
        jPanel1.add(type);
        type.setBounds(229, 150, 140, 20);
        jPanel1.add(weight);
        weight.setBounds(600, 150, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/Download_Copy_Space_Wooden_Background_With_Fruits_for_free.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 900, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  int row = jTable1.getSelectedRow();
        DefaultTableModel hh  =(DefaultTableModel) jTable1.getModel();
          u_name.setText(hh.getValueAt(row, 0).toString());
            name.setText(hh.getValueAt(row, 1).toString());
              id.setText(hh.getValueAt(row, 2).toString());
        type.setText(hh.getValueAt(row, 3).toString());
        weight.setText(hh.getValueAt(row, 4).toString());
       height.setText(hh.getValueAt(row, 5).toString());
        gender.setText(hh.getValueAt(row, 6).toString());
         age.setText(hh.getValueAt(row, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
      char [] arr=id.getText().toCharArray();
       
      
     
        if (id.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Please Enter Member's ID First", "ERROR",JOptionPane.ERROR_MESSAGE);
      }
      
      else if ((arr[0]>=65&&arr[0]<=90)|| (arr[0]>=97&&arr[0]<=122)){
           JOptionPane.showMessageDialog(null,"Please Enter An Integer ID", "ERROR",JOptionPane.ERROR_MESSAGE);
                id.setText("");
              }
      else {
          id_check = e.search(Integer.valueOf(id.getText()));
          if (id_check ==-1){
               JOptionPane.showMessageDialog(null,"Member's ID Not Found", "ERROR",JOptionPane.ERROR_MESSAGE);
               id.setText("");
          }
          else {
              
               DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
               model.setRowCount(0);
       Object rowData[] = new Object[8];
      
          
      
         rowData[0]=  e.members.get(id_check).getUser_name();
      
           rowData[1]=  e.members.get(id_check).getName();
            rowData[2]=  e.members.get(id_check).getMember_id();
           rowData[3]=   e.members.get(id_check).getType();
             rowData[4]=   e.members.get(id_check).getHeight();
             rowData[5]=   e.members.get(id_check).getWeight();
               rowData[6]=  e.members.get(id_check).getGender();
           rowData[7]=  e.members.get(id_check).getAge();
           model.addRow( rowData);
      
        
    
              
          
    
              
          }
      }
    }//GEN-LAST:event_search_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed

        int i = jTable1.getSelectedRow();
                  DefaultTableModel hh  =(DefaultTableModel) jTable1.getModel();
                  if (i>=0){
                       hh.setValueAt(u_name.getText(), i, 0);
                      e.members.get(id_check).setUser_name(u_name.getText());
                       hh.setValueAt(name.getText(), i, 1);
                     e.members.get(id_check).setName(name.getText());
                       hh.setValueAt(id.getText(), i, 2);
                       e.members.get(id_check).setMember_id(Integer.valueOf(id.getText()));
                      hh.setValueAt(type.getText(), i, 3);
                    e.members.get(id_check).setType(type.getText());
                      hh.setValueAt(height.getText(), i, 4);
                    e.members.get(id_check).setHeight(Float.valueOf(height.getText()));
                      hh.setValueAt(weight.getText(), i, 5);
                     e.members.get(id_check).setWeight(Float.valueOf(weight.getText()));
                       hh.setValueAt(gender.getText(), i, 6);
                       e.members.get(id_check).setGender(gender.getText());
                        hh.setValueAt(age.getText(), i, 7);
                         e.members.get(id_check).setAge(Float.valueOf(age.getText()));
                                    
                  }
                  else {
                      JOptionPane.showMessageDialog(null,"ERROR", "ERROR",JOptionPane.ERROR_MESSAGE);
                  }
    }//GEN-LAST:event_edit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_memb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_memb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_memb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_memb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_memb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField height;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel n;
    private javax.swing.JTextField name;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField type;
    private javax.swing.JTextField u_name;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
