/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;

import static bestproject.Login.search3;
import static bestproject.employee.members;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class mem_op extends javax.swing.JFrame {
member m = new member ();
    /**
     * Creates new form mem_op
     */
    public mem_op() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dia_button = new javax.swing.JButton();
        report_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Diet routine");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 190, 250, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 440, 130, 50);

        dia_button.setBackground(new java.awt.Color(0, 0, 0));
        dia_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dia_button.setForeground(new java.awt.Color(255, 255, 255));
        dia_button.setText("Exercise routine ");
        dia_button.setToolTipText("");
        dia_button.setName(""); // NOI18N
        dia_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(dia_button);
        dia_button.setBounds(210, 280, 230, 50);

        report_button.setBackground(new java.awt.Color(0, 0, 0));
        report_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        report_button.setForeground(new java.awt.Color(255, 255, 255));
        report_button.setText("Report");
        report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(report_button);
        report_button.setBounds(10, 360, 250, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/o.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       diet_rot a=new diet_rot();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        AdminorUser a=new AdminorUser();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dia_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_buttonActionPerformed
             int i=Login.search3(Login.text_name.getText(), Login.text_Password.getText());
         m.suitable_exercise(members.get(i).getType()); 
           this.dispose();
    }//GEN-LAST:event_dia_buttonActionPerformed

    private void report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_buttonActionPerformed

         int i=Login.search3(Login.text_name.getText(), Login.text_Password.getText());
       if(members.get(i).getType().equals("football player"))
       {
           JOptionPane.showMessageDialog(null, "Running 3 miles every day is a great cardiovascular"
                   + " workout and will help keep you at your peak fitness.\n" +
                     "Do exercises to increase your speed. Find a drop of around 150cm "
                   + "or stand on a barrel or safe object of a similar height.\n" +
                     "Learn to play with both feet, Devote yourself to football, Start playing "
                   + "at a young age, and practice regularly Stepwise practice,\n"
                   + " be patient, Rate yourself as a player, Strive to be the best,\n"
                   + " Communication with others,"
                   + " Fitness, Continue individual training, Be mentally strong ");
       }
       else if (members.get(i).getType().equals("swimming player"))
       {
           JOptionPane.showMessageDialog(null, "Don’t get in the pool and begin swimming lengths"
                   + " before you are warmed up. "
                   + " Start your session by gliding for a few minutes; this gets the blood flowing"
                   + " and your body gets used to being in the water.\n"
                   + " After you’ve done some gliding, try going on your side and getting some breathing practice."
                   + " Breathing is the key to a successful stroke, and the more time you can"
                   + " spend perfecting your technique, the better. \n"
                   + " Most swimming pools now have allocated lane sessions when the lanes are sectioned off."
                   + " Outside of lane sessions you could be"
                   + " weaving in and out of other swimming pool users which can be really frustrating!. \n"
                   + " You should wash your swimming gear thoroughly after each swim to "
                   + " ensure that you are getting rid of the chlorine."
                   + " This will help prolong its life.\n"
                   + " Choose carefully and make sure you aren’t just buying what looks good but what is"
                   + " actually practical. Some swimsuits"
                   + " and trunks from trendy boutiques might look great but could"
                   + " lose their shape or fade after a few swims.\n"
                   + " Go to any of the DIY warehouses and buy one of the plastics tubs that you use for home storage."
                   + " Throwing wet gear into one after a swim is a lot more sensible than"
                   + " putting it into a sports bag.\n"
                   + " Regular use of a heavily chlorinated pool can affect your scalp and on occasions make it flake. You can"
                   + " avoid this by wearing an inexpensive cap — it can make all the difference.\n"
                   + " If you feel like you can never get warmed up in the water then invest in a lined top as it can significantly increase your "
                   + " enjoyment of your swimming.\n"
                   + " Make sure it is a close fit without restricting movement."
                   + " Pool temperatures can vary considerably so don’t assume you can wear the same in each.\n");
       }
       else if(members.get(i).getType().equals("diabetes patient"))
       {
            JOptionPane.showMessageDialog(null, "There are different types of diabetes,"
                    + " and no two people with diabetes are the same.\n" +
                    " So there isn’t a one-size-fits-all 'diabetes diet' for everyone with diabetes.\n" +
                    " But we’ve come up with tips that you can use to help you make healthier food choices. \n" +
                    "These healthy eating tips are general and can help you manage your blood glucose (sugar),"
                    + " blood pressure and cholesterol levels.\n" +
                    " They can also help you manage your weight and reduce the risk of diabetes complications, \n" +
                    "such as heart problems and strokes, and other health conditions including certain types of cancers. \n" +
                    "“Making healthier food choices is important to manage your diabetes "
                    + "and to reduce your risk of diabetes complications.\n" +
                    " We know that not everyone agrees on what is the best diet.\n" +
                    " This is why we’ve reviewed all the evidence to put these tips together.\n" +
                    " We’ve focused on specific foods, to make it easier for you to put "
                    + "these tips into practice and to complement whatever diet you decide to follow.");
       }
       else if(members.get(i).getType().equals("pregnancy"))
       {
            JOptionPane.showMessageDialog(null, "See your practitioner before becoming pregnant.\n" +
                     "Start changing your food habits to include a healthy variety of foods.\n" +
                     "Exercise! Starting now will help you stay in shape during pregnancy, can lower your risk of miscarriage,"
                     + " and has been proven to help reduce labor complications and length.1﻿\n" +
                     "Educate yourself!\n" +
                     "Eat a new vegetable you've never tried.\n" +
                     "Check out a book on pregnancy.\n" +
                     "Decide what you'd like to do about birth control."
                     + " You may need to find out how quickly after stopping birth control you can get pregnant,\n"
                     + " or how you would plan to get pregnant in conjunction with "
                     + "stopping your current contraception pills or birth control devices.\n" +
                     "Quit smoking. There are many programs to help you.\n" +
                     "Take a prenatal vitamin. They can be prescribed by your practitioner or"
                     + " you can buy them over the counter. Ensure it contains 0.4 mg of folic acid.\n"
                     + "Avoid chemicals that could possibly harm a developing fetus. Learn about the common dangerous"
                     + " chemicals that could be lurking in your home, work place, and community.\n" +
                     "See your dentist before you get pregnant and brush your teeth daily.\n" +
                     "Tell any medical professional that you may be pregnant if you"
                     + " are trying to get pregnant. This can prevent exposure to harmful tests "
                     + "and chemicals if you are pregnant and don't know it yet.\n"
                     + "Act pregnant. This includes not drinking alcohol, even while trying to conceive. There is no"
                     + " known safe level during pregnancy and alcohol can cause birth defects.");
       }
    }//GEN-LAST:event_report_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mem_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mem_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mem_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mem_op.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mem_op().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton dia_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton report_button;
    // End of variables declaration//GEN-END:variables

    private int returnmemberindex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
