/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;

import static bestproject.Admin.employees;
//import static bestproject.employee.members;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class register_mem extends javax.swing.JFrame {
ButtonGroup bg1 = new ButtonGroup( );

  String n;
    public register_mem() {
      //  initComponents();
         initComponents();
        this.setLocationRelativeTo(null);
        bg1.add(male_btn);
        bg1.add(female_btn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        submit_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        height_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        weight_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        re_pass = new javax.swing.JPasswordField();
        tybe_text = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(name);
        name.setBounds(630, 40, 150, 30);
        jPanel1.add(id);
        id.setBounds(630, 0, 150, 30);
        jPanel1.add(age);
        age.setBounds(630, 80, 150, 30);
        jPanel1.add(user_name);
        user_name.setBounds(630, 120, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 0, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 40, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 80, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User_Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 120, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 160, 80, 30);

        male_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male_btn.setText("Male");
        jPanel1.add(male_btn);
        male_btn.setBounds(640, 360, 90, 25);

        female_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female_btn.setText("Female");
        jPanel1.add(female_btn);
        female_btn.setBounds(640, 400, 93, 23);

        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_btn.setText("Add");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn);
        submit_btn.setBounds(490, 430, 140, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Re_enter Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 200, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 370, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("type");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 240, 60, 30);

        height_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height_textActionPerformed(evt);
            }
        });
        jPanel1.add(height_text);
        height_text.setBounds(630, 320, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("height");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 320, 70, 30);

        weight_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_textActionPerformed(evt);
            }
        });
        jPanel1.add(weight_text);
        weight_text.setBounds(630, 280, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("weight");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 280, 60, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<<   Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 430, 110, 50);
        jPanel1.add(pass);
        pass.setBounds(630, 160, 150, 30);
        jPanel1.add(re_pass);
        re_pass.setBounds(630, 200, 150, 30);

        tybe_text.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "football player", "swimming player", "pregnancy", "diabetes patient" }));
        tybe_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tybe_textActionPerformed(evt);
            }
        });
        jPanel1.add(tybe_text);
        tybe_text.setBounds(630, 240, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/proo1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-50, -10, 900, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
                boolean continu =true;
                boolean check=false;
        while(continu)
        {
            continu=false;
        try{
                       if (id.getText().equals("")||name.getText().equals("")||age.getText().equals("")
                               || weight_text.getText().equals("")|| height_text.getText().equals("")||user_name.getText().equals("")||pass.getText().equals("")||re_pass.getText().equals(""))
                          throw new Error("Please Enter The Empty Fields.");
                       
                       }
                    catch(Error ex){
                          check = true;
                          //continu=true;
                        JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "WARNING",  JOptionPane.WARNING_MESSAGE);
                    }
                    try{
                    
                    if(!age.getText().equals(""))
                        {
                         if (Integer.valueOf(age.getText())<0)
                         throw new Error("The Age must be postive"); 
                        }
                    }
                   catch(Error ex){
                   
                   check=true;
                  // continu=true;
                    JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "WARING",  JOptionPane.WARNING_MESSAGE);
                   }
                    //
                    try{
                    if(pass.getText().contains(" ")||re_pass.getText().contains(" "))
                        {
                            throw new Error("Password should not contain any space"); 
                        }
                    }
                    catch(Error ex){
                          check = true;
                          //continu=true;
                          JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Password Erorr",  JOptionPane.WARNING_MESSAGE);
                      }
                     //
                    try{
                          if (!pass.getText().equals(re_pass.getText()))
                           throw new Error("The Password You Entered In The Second Time Doesn't Match The First Time"); 
                      }
                      catch(Error ex){
                          check = true;
                         // continu=true;
                          JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Password Dismatch",  JOptionPane.WARNING_MESSAGE);
                      }
                      try{
                             if(!male_btn.isSelected() && !female_btn.isSelected() )
                                 throw new Error("Must Select member Type");
                         }
                      catch(Error ex){
                            check = true;
                           // continu=true;
                            JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Select Type",  JOptionPane.WARNING_MESSAGE);
                         }
                         if(male_btn.isSelected()){
                     n="male";
                     }
                     else 
                         
                         if(female_btn.isSelected()){
                     n="female";
                     }
                         
                 
                     if (!check){
                     employee m= employees.get(Login.index);
                      if( m.add(Integer.valueOf(id.getText()), Integer.valueOf(weight_text.getText()), Integer.valueOf(height_text.getText()),tybe_text.getSelectedItem().toString(), name.getText(), n, Integer.valueOf(age.getText()),user_name.getText(),pass.getText()))
                          id.setText("");
                           name.setText("");
                           user_name.setText("");
                           pass.setText("");
                           re_pass.setText("");
                           bg1.clearSelection();
                           weight_text.setText("");
                           height_text.setText("");
                           tybe_text.setSelectedIndex(0);
                           age.setText("");
                          // continu=false;
                     }
                  
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         operatione_emp a=new operatione_emp();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void height_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height_textActionPerformed

    private void weight_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight_textActionPerformed

    private void tybe_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tybe_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tybe_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_mem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_mem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JTextField height_text;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField re_pass;
    private javax.swing.JButton submit_btn;
    private javax.swing.JComboBox tybe_text;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField weight_text;
    // End of variables declaration//GEN-END:variables

//    private Component getFrame() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
 //private register_emp getFrame(){return this;
    private   register_mem getFrame() {return this;}


         //To change body of generated methods, choose Tools | Templates.
    
}
