/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class register_emp extends javax.swing.JFrame {
 ButtonGroup bg1 = new ButtonGroup( );
  String n;
    public register_emp() {
        initComponents();
        this.setLocationRelativeTo(null);
        bg1.add(male_btn);
        bg1.add(female_btn);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        submit_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        re_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 520));

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 494));
        jPanel1.setLayout(null);
        jPanel1.add(name);
        name.setBounds(640, 80, 150, 30);
        jPanel1.add(id);
        id.setBounds(640, 30, 150, 30);
        jPanel1.add(age);
        age.setBounds(640, 130, 150, 30);
        jPanel1.add(user_name);
        user_name.setBounds(640, 180, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 30, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 80, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 130, 27, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User_Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 180, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 230, 90, 30);

        male_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male_btn.setText("Male");
        jPanel1.add(male_btn);
        male_btn.setBounds(650, 340, 130, 25);

        female_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female_btn.setText("Female");
        jPanel1.add(female_btn);
        female_btn.setBounds(650, 380, 130, 20);

        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_btn.setText("Add");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn);
        submit_btn.setBounds(520, 430, 120, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Re_enter Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 280, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(540, 350, 80, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 400, 90, 30);
        jPanel1.add(pass);
        pass.setBounds(640, 230, 150, 30);
        jPanel1.add(re_pass);
        re_pass.setBounds(640, 280, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/proo1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 910, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
    boolean continu =true;
    boolean check=false;
            while(continu)
        {
            continu=false;
                    try{
                       if (id.getText().equals("")||name.getText().equals("")|| age.getText().equals("")||user_name.getText().equals("")||pass.getText().equals("")||re_pass.getText().equals(""))
                          throw new Error("Please Enter The Empty Fields.");
                       
                       }
                    catch(Error ex){
                          check = true;
                         // continu=true;
                        JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "WARNING",  JOptionPane.WARNING_MESSAGE);
                    }
                    try{
                        if(!age.getText().equals(""))
                        {
                         if (Integer.valueOf(age.getText())<0)
                         throw new Error("The Age must be postive"); 
                        }
                    }
                   catch(Error ex){
                   
                   check=true;
                   //continu=true;
                    JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "WARING",  JOptionPane.WARNING_MESSAGE);
                   }
                    //
                    try{
                    if(pass.getText().contains(" ")||re_pass.getText().contains(" "))
                        {
                            throw new Error("Password should not contain any space"); 
                        }
                    }
                    catch(Error ex){
                          check = true;
                        //  continu=true;
                          JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Password Erorr",  JOptionPane.WARNING_MESSAGE);
                      }
                    //
                    try{
                        
                          if (!pass.getText().equals(re_pass.getText()))
                           throw new Error("The Password You Entered In The Second Time Doesn't Match The First Time"); 
                      }
                      catch(Error ex){
                          check = true;
                         
                          JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Password Erorr",  JOptionPane.WARNING_MESSAGE);
                      }
                      try{
                             if(!male_btn.isSelected() && !female_btn.isSelected() )
                                 throw new Error("Must Select Employee Type");
                         }
                      catch(Error ex){
                            check = true;
                          //  continu=true;
                            JOptionPane.showMessageDialog(getFrame(), ex.getMessage(), "Must Select Employee Type",  JOptionPane.WARNING_MESSAGE);
                         }
                         if(male_btn.isSelected()){
                     n="male";
                     }
                     else 
                         
                         if(female_btn.isSelected()){
                     n="female";
                     }
                     
                     if (!check){
                        Admin a=new Admin("Admin", "admin");
                      if(a.add(name.getText(), n, Float.parseFloat(age.getText()), user_name.getText(), pass.getText(), Integer.valueOf(id.getText())))
                         JOptionPane.showMessageDialog(getFrame(), " ADDED SUCCUSSFULY", "SUCCUFULL",  JOptionPane.INFORMATION_MESSAGE);
                           id.setText("");
                           name.setText("");
                           user_name.setText("");
                           pass.setText("");
                           re_pass.setText("");
                           bg1.clearSelection();
                           age.setText("");
                           
                     }
                  
                    
        }     
    }//GEN-LAST:event_submit_btnActionPerformed
 
    private register_emp getFrame(){return this;}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       operation_admin a=new  operation_admin();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField re_pass;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
