/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bestproject;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
 public class Login extends javax.swing.JFrame {

    static int index;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text_name = new javax.swing.JTextField();
        text_Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        member = new javax.swing.JButton();
        regemployee = new javax.swing.JButton();
        regmember = new javax.swing.JButton();
        back = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        text_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameActionPerformed(evt);
            }
        });
        jPanel1.add(text_name);
        text_name.setBounds(610, 130, 160, 30);

        text_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(text_Password);
        text_Password.setBounds(610, 180, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 190, 80, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 120, 90, 40);

        member.setBackground(java.awt.Color.black);
        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Login M");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jPanel1.add(member);
        member.setBounds(630, 300, 90, 30);

        regemployee.setBackground(new java.awt.Color(0, 0, 0));
        regemployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regemployee.setForeground(new java.awt.Color(255, 255, 255));
        regemployee.setText("Register E");
        regemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regemployeeActionPerformed(evt);
            }
        });
        jPanel1.add(regemployee);
        regemployee.setBounds(500, 260, 130, 25);

        regmember.setBackground(new java.awt.Color(0, 0, 0));
        regmember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regmember.setForeground(new java.awt.Color(255, 255, 255));
        regmember.setText("Register M ");
        regmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regmemberActionPerformed(evt);
            }
        });
        jPanel1.add(regmember);
        regmember.setBounds(500, 300, 120, 25);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("< Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(0, 430, 90, 30);

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Login A");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin);
        admin.setBounds(630, 220, 90, 30);

        employee.setBackground(new java.awt.Color(0, 0, 0));
        employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.setText("Login E");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee);
        employee.setBounds(630, 260, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestproject/WhatsApp Image 2020-03-30 at 4.34.55 AM.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nameActionPerformed

    private void text_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PasswordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
   AdminorUser uu=new AdminorUser();
uu.setVisible(true);
uu.pack();
uu.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void regemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regemployeeActionPerformed
 register_emp uu=new  register_emp();
uu.setVisible(true);
uu.pack();
uu.setLocationRelativeTo(null);
this.dispose();        
    }//GEN-LAST:event_regemployeeActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
       if("".equals(text_name.getText())||"".equals(text_Password.getText()))
       {
        JOptionPane.showMessageDialog(null, "please enter your Name &Password please");
       }
       else{
           
       if( "Admin".equals(text_name.getText())&&  "admin".equals(text_Password.getText())){
       
   JOptionPane.showMessageDialog(null, "Done you ara Admin");
   operation_admin a= new operation_admin();
   a.setVisible(true);
a.pack();
a.setLocationRelativeTo(null);
this.dispose();
   
       }
       else 
         JOptionPane.showMessageDialog(null, "check your Name and Password ");
    }//GEN-LAST:event_adminActionPerformed
    }
    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
       if("".equals(text_name.getText())||"".equals(text_Password.getText()))
       {
        JOptionPane.showMessageDialog(null, "please enter your Name &Password please");
       }
       else
       {
           Admin admin =new Admin("Admin", "admin");
      // employee e  = new employee(text_name.getText(), text_Password.getText());
        index =  admin.search2(text_name.getText(), text_Password.getText());
         
// employee.search2("", "");

       if(index != -1)
       {
       JOptionPane.showMessageDialog(null, "Wellcome employee "+text_name.getText());
       
       operation_emp a= new operation_emp();
       a.setVisible(true);
       a.pack();
       a.setLocationRelativeTo(null);
       this.dispose();
       }
        else 
         JOptionPane.showMessageDialog(null, "check your Name and Password ");
       }
    }//GEN-LAST:event_employeeActionPerformed

    private void regmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regmemberActionPerformed
       
      Delete_mem e=new Delete_mem();
      e.setVisible(true);
      e.pack();
      e.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_regmemberActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton admin;
    private javax.swing.JButton back;
    public javax.swing.JButton employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton member;
    public javax.swing.JButton regemployee;
    public javax.swing.JButton regmember;
    private javax.swing.JPasswordField text_Password;
    private javax.swing.JTextField text_name;
    // End of variables declaration//GEN-END:variables
}
